fix main, add TTMLIRSupport to ttmlir_export_targets (#6122)
### Problem description
1. Main is broken.
2. Doc build is broken (with some specific flags).

### What's changed
1. Add `TTMLIRSupport` to `ttmlir_export_targets`
2. Fixes doc build.

### Checklist
- [X] New/Existing tests provide coverage for changes

### Repdroduction
- **Machine and docker img info:** `ird reserve --docker-image mlir
wormhole_b0 --machine aus-wh-08 --model x1`
- **Branch:** tt-mlir's main (a46d9ffdffd05fb3bd9b33cd77c6332fcee0c6f5)
- **Fresh build and fresh metal:** `rm -rf build && rm -rf
third_party/tt-metal`
- **Build flags:** `cmake -G Ninja -B build -DTTMLIR_ENABLE_RUNTIME=ON
-DTTMLIR_ENABLE_BINDINGS_PYTHON=ON -DTTMLIR_ENABLE_TTNN_JIT=ON`
- **Error:**
```
CMake Error in cmake/modules/CMakeLists.txt:
  install(EXPORT "TTMLIRTargets" ...) includes target "TTMLIRCompilerStatic"
  which requires target "TTMLIRSupport" that is not in any export set.
```
- **Fix:** Added TTMLIRSupport
[here](https://github.com/tenstorrent/tt-mlir/blob/a46d9ffdffd05fb3bd9b33cd77c6332fcee0c6f5/cmake/modules/TTMLIRInstall.cmake#L76-L79).

### Things to follow up:
There's another error after this (during `cmake --build build` when
building `tt_alchemist.cpp.o`):
```
/localdev/sgholami/tt-mlir/tools/tt-alchemist/csrc/lib/tt_alchemist.cpp:17:10: fatal error: 'shardy/dialect/sdy/ir/dialect.h' file not found
   17 | #include "shardy/dialect/sdy/ir/dialect.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
@svuckovicTT will submit a fix for that.
- **Temporary solution for this:** Added `DTTMLIR_ENABLE_STABLEHLO=ON`
flag.


----

### Doc build:
@brataTT suggested to test the doc build.
Initially, I tried with `cmake -G Ninja -B build
-DTTMLIR_ENABLE_RUNTIME=ON -DTTMLIR_ENABLE_BINDINGS_PYTHON=ON
-DTTMLIR_ENABLE_TTNN_JIT=ON -DTTMLIR_ENABLE_STABLEHLO=ON` and then
`cmake -- build build -- docs` failed with several errors (missing
`mdbook` + removing some duplicates). See the full logs here: [doc build
errors.txt](https://github.com/user-attachments/files/23885797/doc.build.errors.txt)
I fixed those in
[this](https://github.com/tenstorrent/tt-mlir/pull/6122/commits/123457a5c39f4a4b33e17e0cc0973e791d648d47)
commit too.


**Why was this not observed in CI ?**
Probably because we build the docs with just these flags in
[CI](https://github.com/tenstorrent/tt-mlir/blob/a46d9ffdffd05fb3bd9b33cd77c6332fcee0c6f5/.github/workflows/call-build-docs.yml#L68-L71):
```
cmake -G Ninja -B build
cmake --build build --docs
```
But I experienced the errors with these flags:
```
cmake -G Ninja -B build -DTTMLIR_ENABLE_RUNTIME=ON -DTTMLIR_ENABLE_BINDINGS_PYTHON=ON -DTTMLIR_ENABLE_TTNN_JIT=ON -DTTMLIR_ENABLE_STABLEHLO=ON
cmake --build build --docs
```
Therefore, by using `DTTMLIR_ENABLE_STABLEHLO=ON` I'm also triggering
the doc builds for `stablehlo` related targets (which caused the
errors).